### DISCUSSION TITLE
Client model generated from type object with additionalProperties not correctly deserialized

### DISCUSSION THREAD

**Discussion by uvoigt** [micronaut-projects/micronaut-openapi#1852] [Q&A] [answered]
Hi,

with
```
    LocStringDto:
      required:
      - values
      type: object
      properties:
        values:
          type: object
          additionalProperties:
            type: string
``` 

it generates a field and constructor

```
    @NotNull
    @JsonProperty(JSON_PROPERTY_VALUES)
    private Map<String, @NotNull String> values;

    public LocStringDto(Map<String, String> values) {
        this.values = values;
    }
``` 

which constructs a null value map from this string

```
{
  "en" : "Test 1",
  "de" : "Test 2"
}

``` 

Is there any option that I am not aware of to create code that would be able to read that data?
