### ISSUE TITLE
Schema oneOf ignored on properties

### ISSUE THREAD

**Issue by lightbody** [micronaut-projects/micronaut-openapi#1023]
### Expected Behavior

See link demo project. I would expect that `demo-0.0.yml` would end with this:

```yml
components:
  schemas:
    Wrapper:
      type: object
      properties:
        value:
          - type: string
          - type: object
          - type: boolean
```

### Actual Behaviour

The `oneOf` property isn't used and instead the `Wrapper.value` field is expressed as simply `object`:

```yml
components:
  schemas:
    Wrapper:
      type: object
      properties:
        value:
          type: object
```

### Steps To Reproduce

Build the link demo.

### Example Application

https://github.com/lightbody/micronaut-openapi-oneOf-bug

### Version

all
