### ISSUE TITLE
Add info about security & OpenAPI

### ISSUE THREAD

**Issue by witek1902** [micronaut-projects/micronaut-openapi#104]
Add info about security. How can I use `intercept-url-map` to create unsecured OpenAPI docs: https://micronaut-projects.github.io/micronaut-security/snapshot/guide/#interceptUrlMap

Example:
```
  security:
    enabled: true
    intercept-url-map:
      - pattern: /swagger/**
        access:
          - isAnonymous()
      - pattern: /swagger-ui/**
        access:
          - isAnonymous()
```
