### ISSUE TITLE
Swagger UI 404 on Google Cloud Run

### ISSUE THREAD

**Issue by amarekosistem** [micronaut-projects/micronaut-openapi#1078]
### Issue description

**NEED HELP / GUIDANCE** 

**Expected** :
- when open url /swagger-ui it should be showing

**Problem** : 
- If trying to open swagger-ui from **localhost** everything is working well, but when deploying it **Cloud Run** neither /swagger and /swagger-ui can be open, both is giving 404. But when trying to open /swagger/*.yml , it can be open and show all json stuff regarding this api.
Could some one guide me where i make mistake here ? because no error just 404 on google cloud run

This is my router setting :
```
 router:
    static-resources:
      default:
        enabled: true
        mapping: /**
        paths: classpath:swagger
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
```

This is my openapi.properties :
```
endpoints.enabled=true
swagger-ui.enabled=true
redoc.enabled=false
rapidoc.enabled=false
rapidoc.bg-color=#14191f
rapidoc.text-color=#aec2e0
rapidoc.sort-endpoints-by=method
```

Thank you before
