### ISSUE TITLE
Issue loading swagger-ui in micronaut 3.10.1 with http://localhost:8080/demo/swagger-ui

### ISSUE THREAD

**Issue by ak10o** [micronaut-projects/micronaut-openapi#1189]
### Expected Behavior

The swagger-ui page should be loaded when invoked with the url http://localhost:8080/demo/swagger-ui

### Actual Behaviour

The page is blank, when we inspected then we saw some 404 error

![image](https://github.com/micronaut-projects/micronaut-openapi/assets/26184920/8ebffc12-a68e-4c3b-8316-4224192e1c2a)

### Steps To Reproduce

1. Create a micronaut demo app from https://micronaut.io/launch/
2. Select micronaut version 3.10.1
3. Add OpenAPI and Swagger as part of the feature
4. Select java 11 , gradle as build tool and junit as test framework
5. Modify the application.yml to prefix "demo" in the mapping attribute

micronaut:
application:
name: demo
router:
static-resources:
swagger:
paths: classpath:META-INF/swagger
mapping: /demo/swagger/
swagger-ui:
paths: classpath:META-INF/swagger/views/swagger-ui
mapping: /demo/swagger-ui/

6. Modified the openapi.properties

swagger-ui.enabled=true
redoc.enabled=false
rapidoc.enabled=false
rapidoc.bg-color=#14191f
rapidoc.text-color=#aec2e0
rapidoc.sort-endpoints-by=method

micronaut.openapi.views.spec=mapping.path=/demo/swagger

### Environment Information

Operating System: Mac
Micronaut Version: 3.10.1
JDK Version: 11

### Example Application

Although with the below configuration we can load the swagger-ui with the url http://localhost:8080/swagger-ui  Application.yml  micronaut: application: name: demo router: static-resources: swagger: paths: classpath:META-INF/swagger mapping: /swagger/ swagger-ui: paths: classpath:META-INF/swagger/views/swagger-ui mapping: /swagger-ui/  And openapi.properties  swagger-ui.enabled=true redoc.enabled=false rapidoc.enabled=false rapidoc.bg-color=#14191f rapidoc.text-color=#aec2e0 rapidoc.sort-endpoints-by=method  micronaut.openapi.views.spec=mapping.path=/swagger

### Version

3.10.1

**Comment by altro3** [comment]
@ak10o It's not a bug, just a specific work. All what you need to change in your confiuration for right work: just chnage value of `micronaut.openapi.views.spec` to right value like this:
```properties
micronaut.openapi.views.spec=mapping.path=/demo/swagger,swagger-ui.js.url=/demo/swagger-ui/res/
```
You have a problem because you have overridden the path to index.html , but you have not overridden the path to the resources that are included in the jar file and are copied to the `/swagger-ui/res/` directory.

In general, this is not automatic and if you change the mapping.path you need to explicitly change the path to the resource files

**Comment by altro3** [comment]
@ak10o I mean, ou have a poblem, because you change mapping in yaml file here:

```yaml
micronaut:
  router:
    static-resources:
      swagger-ui:
        mapping: /demo/swagger-ui/
```

Second solution: you can set path to resources too  like this:
```yaml
micronaut:
  router:
    static-resources:
      swagger-ui:
        mapping: /demo/swagger-ui/
      swagger-ui-res:
        paths: classpath:META-INF/swagger/views/swagger-ui/res
        mapping: /swagger-ui/res

```
