### ISSUE TITLE
Date Field Examples do not respect Jackson writeDatesAsTimestamps setting

### ISSUE THREAD

**Issue by jdaugherty** [micronaut-projects/micronaut-openapi#124]
**Issue**
Date fields that have an example defined are being expanded as if the jackson writeDatesAsTimestamp is set to true.  

**How to reproduce**
Example project is located here: https://github.com/jdaugherty/openapi-date-example-issue.  Running ./gradlew check and opening the yaml file will show the birthdate field has an invalid example.  The annotation on the birthdate field in the Pet domain class has an example value of **2020-07-21T17:32:28Z** while the yaml file will show a nested structure.  

Note:
application.yml, has jackson writeDatesAsTimestamps set to false.

**Example (Bad) Yaml**
Generated Yaml file has an example as if writeDatesAsTimestamps was turned on.  
```
example: 
    offset:
      totalSeconds: 0
      id: Z
      rules:
        transitions: []
        transitionRules: []
        fixedOffset: true
    dayOfYear: 203
    dayOfWeek: TUESDAY
    nano: 0
    monthValue: 7
    dayOfMonth: 21
    hour: 17
    minute: 32
    second: 28
    year: 2020
    month: JULY
```

**Expected Behavior**
Yaml produced should show 
```
example: 2020-07-21T17:32:28Z
```
