### ISSUE TITLE
Cannot change swagger ui to http://localhost:8080/openapi instead of /swagger/views/swagger-ui

### ISSUE THREAD

**Issue by subash89** [micronaut-projects/micronaut-openapi#1262]
### Expected Behavior

I tried following like router config to get swagger ui at /openapi. But UI does not work and gives 404.
 And when I build it, in target folder, it's always the META-INF/swagger/views/swagger-ui getting created. looks like this swagger/views/swagger-ui path is hard coded somewhere?

```
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /openapi/**
```

### Actual Behaviour

I am getting  404 for  http://localhost:8080/openapi.

### Steps To Reproduce

1. Create  router config as above
2. Start server.
3. Swagger UI not appearing at  http://localhost:8080/openapi 

### Environment Information

JDK 17

### Version

4.1.0
