### ISSUE TITLE
`Iterable`/`Array` field with generics lost `T` type which inherit from class

### ISSUE THREAD

**Issue by JaneWardSandy** [micronaut-projects/micronaut-openapi#1288]
### Expected Behavior

When controller return type with generics, like `ListElement<String>`

```java
@Get
public ListElement<String> list() {
    return null;
}

public class ListElement<T> {
    public T typeValue;
    public Iterable<T> IterableValues;
    public T[] arrayValues;
}
```

`T` should be inherit from type

```yml
components:
  schemas:
    ListElement_String_:
      type: object
      properties:
        typeValue:
          type: string
        IterableValues:
          type: array
          items:
            type: string
        arrayValues:
          type: array
          items:
            type: string
```

### Actual Behaviour

`Iterable<T>` lost `T` type, and `T[]` was lost `array`

```yml
components:
  schemas:
    ListElement_String_:
      type: object
      properties:
        typeValue:
          type: string
        IterableValues:
          type: array
          items:
            type: object
        arrayValues:
          type: string
```

### Steps To Reproduce

1. Define class `ListElement`

```java
public class ListElement<T> {
    public T typeValue;
    public Iterable<T> IterableValues;
    public T[] arrayValues;
}
```

2. Define simple controller method

```java
@Get
public ListElement<String> list() {
    return null;
}
```

3. run gradle task `classes` / `build`, see the swagger `yaml` file

### Environment Information

- MacOS
- JDK 17 (Graal)

### Version

4.1.6

**Comment by graemerocher** [comment]
looks like a bug, might be better to use a `record` instead of public mutable fields

**Comment by altro3** [comment]
@graemerocher yeah, it is a bug, but in core

**Comment by altro3** [comment]
@JaneWardSandy I confirm: if you use record , then everything will work correctly

**Comment by altro3** [comment]
@graemerocher @JaneWardSandy Also it works fine if you use getters / setters. Problem only with public fields

**Comment by altro3** [comment]
@radovanradic I think, this is micronaut-data bug

**Comment by JaneWardSandy** [comment]
@altro3 There are still problems here. As I mentioned at the beginning, it will also lose the definition of arrays.

For example, if the initial array definition is defined, first change it to code that can correctly obtain the paradigm.
```java
private T[] arrayValues;

public T[] getArrayValues() {
  return arrayValues;
}
```
Or Kotlin
```kotlin
val arrayValues: Array<T>
```

The result is not considered an array.
```yml
arrayValues:
  type: string
```

And we set the paradigm as the basic type (such as `int`,`long`,`boolean`) (except `String`) but can correctly output as `array`
```yml
arrayValues:
  type: array
  items:
    type: boolean
```
