### ISSUE TITLE
Swagger built-in themes are not working

### ISSUE THREAD

**Issue by bacca87** [micronaut-projects/micronaut-openapi#1352]
### Issue description

If you want change the swagger theme using the parameter `swagger-ui.theme`, no matter what you put in, only the default one (flattop.css) is used.

MATERIAL, FEELING_BLUE, MONOKAI, MUTED, NEWSPAPER, OUTLINE, DARK, DARK2 are not working at all.

The guide i followed: https://micronaut-projects.github.io/micronaut-openapi/latest/guide/#swaggerui

Micronaut 4.2.1
io.micronaut.openapi:micronaut-openapi:6.1.0
io.swagger.core.v3:swagger-annotations:2.2.19

**Comment by altro3** [comment]
All works fine.
![изображение](https://github.com/micronaut-projects/micronaut-openapi/assets/48474279/7f39e846-e1c9-403b-a7f1-bbc868fb1954)

I think, problems with you configuration.

One of correct variant to configure swagger-ui theme:
```groovy
tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.fork = true
    options.forkOptions.jvmArgs += "-Dmicronaut.openapi.views.spec=swagger-ui.enabled=true,swagger-ui.theme=dark"
}
```

**Comment by bacca87** [comment]
I'm using the swagger-config.yaml file in the project root directory like described [here](https://github.com/swagger-api/swagger-ui/blob/HEAD/docs/usage/configuration.md) but it looks like that is completely ignored...

I put your configuration example inside the build.gradle file and it works as expected.

**Comment by altro3** [comment]
well, micronaut-openapi doesn't support `swagger-config.yaml`. You need to set configuration properties in our format. read manual

**Comment by nooballday** [comment]
Not sure if I also can't read the manual but this does not work.

`application.yml`

```yml
micronaut:
  openapi:
    views:
      spec:
        swagger-ui.enabled: true
        swagger-ui.theme: material

```

**Comment by altro3** [comment]
@nooballday must be:
```yaml
micronaut:
  openapi:
    views:
      spec: "swagger-ui.enabled=true,swagger-ui.theme=material"
```

Don't ask why it's in this format - it just happened that way.
