### ISSUE TITLE
ArraySchema is not resolving

### ISSUE THREAD

**Issue by StephenOTT** [micronaut-projects/micronaut-openapi#140]
Using 1.3.4

```
@field:ArraySchema(
                    arraySchema = Schema(description = "some description"),
                    schema = Schema(name = "some-object", type = "object"),
                    uniqueItems = true)
        val objects: List<SomeCustomClass> = listOf()
```

The arraySchema does not generate against the field as the fields description

**Comment by StephenOTT** [comment]
it seems like the arraySchema is ignored.  If you use @field:Schema it applies

**Comment by StephenOTT** [comment]
@croudet any ideas on where the problem may be?  Happy to get a PR going if needed

**Comment by croudet** [comment]
I am using java and it works:
```java
    @ArraySchema(schema = @Schema(name = "devices", required = false, description = "A list of device's ids"))
    public List<Long> getDevices() {
```
Have you tried to remove the nested `arraySchema`?

**Comment by StephenOTT** [comment]
I will give it a try. But the nested arraySchema is there to describe the list it self, and the schema prop is to define the object(s) types in the list.  So you need both to have descriptions of the list and the lists content

**Comment by StephenOTT** [comment]
@croudet I have tried with @get:ArraySchema and @field:ArraySchema and no luck.
I have also done with just `schema=` and with just `arraySchema=` and it does not work.

If you change your Long to a pojo, does it still work for you?

**Comment by StephenOTT** [comment]
@croudet even something like:

```
        @get:ArraySchema(schema = Schema(name="dog", description = "dog"))
        val someLong: List<Long> = listOf(),
```

it still fails to generate

yaml looks like:

```
        someLong:
          type: array
          items:
            type: integer
            format: int64
```

**Comment by croudet** [comment]
I have made a tentative fix in https://github.com/micronaut-projects/micronaut-openapi/pull/142
If you can give it a try.

**Comment by croudet** [comment]
The fix will only work on classes:
```java
@Schema(description = "Pets")
class Pets {
    @ArraySchema(arraySchema = @Schema(description = "a list of Pets", nullable = false), minItems = 2, schema = @Schema(description = "No", implementation = Pet.class))
    public List<Pet> pets;
}
```

**Comment by croudet** [comment]
In controller I usually use `@ApiResponse`:
```java
    @ApiResponse(responseCode = "200", description = "Returns a list of Repositories.", content = @Content(mediaType = MediaType.APPLICATION_JSON, array = @ArraySchema(schema = @Schema(implementation = Repository.class))))@ArraySchema(schema = @Schema(implementation = Repository.class))))
    public HttpResponse<Flux<Repository>> listRepositories()
```

**Comment by StephenOTT** [comment]
Will give it a try.  @croudet possible similar style of issue to the following? https://github.com/micronaut-projects/micronaut-openapi/issues/141

**Comment by graemerocher** [comment]
@croudet does https://github.com/micronaut-projects/micronaut-openapi/pull/142 resolve this issue?

**Comment by StephenOTT** [comment]
appears to still be broken in 1.4.0

```kotlin
        @ArraySchema(
                arraySchema = Schema(description = "The list of TAXII versions that this API Root is compatible with. The values listed in this property ​MUST match the media types defined in Section​ 1​ .6.8.1​ and MUST​ include the optional version parameter. A value of \"​application/taxii+json;version=2.1\"​ M​UST​ be included in this list to indicate conformance with this specification."),
                schema = Schema(description = "A Taxii Media Type"),
                uniqueItems = true)
        val versions: List<TaxiiMediaType>,

```

only generates

```
        versions:
          type: array
          items:
            $ref: '#/components/schemas/TaxiiMediaType'
```

descriptions for the field, and description for the items in the list do not generate.

**Comment by croudet** [comment]
Just tested the with the following class
```kotlin
package example

import io.swagger.v3.oas.annotations.media.ArraySchema
import io.swagger.v3.oas.annotations.media.Schema

@Schema
class TestClass {
     @field:ArraySchema(
                    arraySchema = Schema(description = "some description", nullable = false, example = "['aaa', 'bbb']"),
                    schema = Schema(type = "string", allowableValues = ["dog", "cat", "snake"], defaultValue = "dog"),
                    minItems = 2,
                    uniqueItems = true)
     val objects: List<String> = listOf()
}
```
And the generated yaml looks good to me:
```yaml
components:
  schemas:
    TestClass:
      type: object
      properties:
        objects:
          minItems: 2
          uniqueItems: true
          type: array
          description: some description
          nullable: false
          example: '[''aaa'', ''bbb'']'
          items:
            type: string
            default: dog
            enum:
            - dog
            - cat
            - snake
```
