### ISSUE TITLE
Parameter Constant Values/allowableValues/enum do not get generated

### ISSUE THREAD

**Issue by StephenOTT** [micronaut-projects/micronaut-openapi#141]
Consider a Operation on a controller function:

```
    @Operation(
            summary = "...",
            description = "....",
            security = [
                SecurityRequirement(name = "basicAuth")
            ],
            parameters = [
                Parameter(name = Headers.ACCEPT, `in` = ParameterIn.HEADER, required = true, schema = Schema(type = "string", allowableValues = ["some-value"] ))
            ]
    )
```

and the docs show: https://swagger.io/docs/specification/describing-parameters/#constant

But the above code will only generate the following yml

```
      parameters:
      - name: Accept
        in: header
        required: true
        schema:
          type: string
```
