### ISSUE TITLE
'hide-components' property not functioning as expected in OpenAPI Explorer view

### ISSUE THREAD

**Issue by danieltex** [micronaut-projects/micronaut-openapi#1411]
### Expected Behavior

Enabling the `hide-components` property for OpenAPI Explorer view should hide the Components section in the UI.

### Actual Behaviour

Despite enabling the 'hide-components' property in the OpenAPI Explorer, the components section remains visible in the UI. 

### Steps To Reproduce

- Create a project with micronaut-openapi
- Add a controller with Swagger annotations:
```kotlin
package com.example

import io.micronaut.http.annotation.Body
import io.micronaut.http.annotation.Controller
import io.micronaut.http.annotation.Post
import io.swagger.v3.oas.annotations.Operation
import io.swagger.v3.oas.annotations.media.Schema
import io.swagger.v3.oas.annotations.responses.ApiResponse
import io.swagger.v3.oas.annotations.responses.ApiResponses

@Controller("/hello")
class HelloWorldController {

    @Post("/greet")
    @Operation(
        summary = "Greet the user",
        description = "Endpoint to greet the user based on the provided name"
    )
    @ApiResponses(
        ApiResponse(responseCode = "200", description = "Successful greeting"),
        ApiResponse(responseCode = "400", description = "Invalid request format")
    )
    fun greet(@Body request: HelloWorldRequest): HelloWorldResponse {
        val greetingMessage = "Hello, ${request.name}!"
        return HelloWorldResponse(greetingMessage)
    }
}

data class HelloWorldRequest(
    @field:Schema(description = "Name to include in the greeting", example = "John")
    val name: String
)

data class HelloWorldResponse(
    @field:Schema(description = "Greeting message")
    val greeting: String
)
```
- Create `openapi.properties` at root and enable **openapi-explorer view** and **hide-components**:
`micronaut.openapi.views.spec=openapi-explorer.enabled=true,openapi-explorer.hide-components=true`
- Configure routes for openapi-explorer:
```yaml
micronaut:
  application:
    name: demo
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      openapi-explorer:
        paths: classpath:META-INF/swagger/views/openapi-explorer
        mapping: /openapi-explorer/**
```
- Run the application and access it at `http://localhost:8080/openapi-explorer`
- Observe there is a Component section:
![image](https://github.com/micronaut-projects/micronaut-openapi/assets/2984131/c5738b6e-5e76-4be5-a19f-a3ad54c6a985)

### Environment Information

- Operation System: Ubuntu 22.04.3 LTS
- Micronaut version: 4.2.4
- Micronaut OpenAPI version: 6.5.1
- JDK Version: OpenJDK 17.0.8

### Example Application

https://github.com/danieltex/micronaut-openapi-example

### Version

4.2.4
