### ISSUE TITLE
Header Parameters in @Operation do not generate in yml

### ISSUE THREAD

**Issue by StephenOTT** [micronaut-projects/micronaut-openapi#145]
using micronaut-open-api 1.3.4

using kotlin 1.3.61

micronaut 1.3.0

consider the following on a controller func

```kotlin
    @Operation(
            summary = "some summary",
            description = "some description",
            security = [
                SecurityRequirement(name = "basicAuth")
            ],
            parameters = [
                Parameter(name = Headers.ACCEPT,
                        `in` = ParameterIn.HEADER,
                        required = true,
                        schema = Schema(type = "string",
                                allowableValues = [SomeClass.SOME_VALUE1, SomeClass.SOME_VALUE2, SomeClass.SOME_VALUE3],
                                defaultValue = SomeClass.SOME_VALUE1))
            ]
    )
```

The Parameters only get generated as:

```yml
      parameters:
      - name: Accept
        in: header
        required: true
        schema:
          type: string
```

The schema is completely skipped.
