### ISSUE TITLE
List example objects should produce a true list in OpenAPI spec

### ISSUE THREAD

**Issue by jjathman** [micronaut-projects/micronaut-openapi#1565]
### Expected Behavior

If I provide an example string on a List/array object which is a JSON representation of a list, then the output of that in the Yaml OpenAPI spec should be a list. Very similar logic to the special logic of an example which is a JSON map.

### Actual Behaviour

The JSON array string is simply output into the yaml file as a string.

### Steps To Reproduce

Create a Java class with this type of structure:

```java
    @Schema(description = "Street lines of the address", example = "[\"123 Main St\", \"Suite 517\"])
    List<String> lines;
```

the Yaml output will look like this:

```yaml
      properties:
        lines:
          type: array
          description: Street lines of the address
          example: "[\"123 Main St\", \"Suite 517\"]"
          items:
            type: string
```

When ideally it would be this:

```yaml
      properties:
        lines:
          type: array
          description: Street lines of the address
          example:
          - 123 Main St
          - Suite 517
          items:
            type: string
```

I think another special case within this code could solve the issue:

```java
        String schemaExample = (String) annValues.get("example");
        if (StringUtils.isNotEmpty(schemaExample)) {
            try {
                schemaToBind.setExample(OpenApiUtils.getConvertJsonMapper().readValue(schemaExample, Map.class));
               // NEW CODE HERE:  Try to read the value as a list and set the example accordingly
            } catch (JsonProcessingException e) {
                schemaToBind.setExample(schemaExample);
            }
        }
```

What makes this difficult is Swagger seems to handle it just fine without this change, however not all tools are as forgiving. 

### Environment Information

Micronaut OpenApi version 6.5.1

### Version

4.3.8
