### ISSUE TITLE
Extra annotations are not added to fields in Kotlin

### ISSUE THREAD

**Issue by adworzynski** [micronaut-projects/micronaut-openapi#1604]
### Expected Behavior

When declaring "x-field-extra-annotation" on schema's properties field, provided annotations should appear on generated field in model.

### Actual Behaviour

Provided annotations are not added to the field.

### Steps To Reproduce

Configured component:
```
SearchCriteria:
  type: object
  properties:
    text:
      x-field-extra-annotation: |-
        @jakarta.validation.constraints.NotBlank
      type: string
```
Generated class:
```
@Serdeable
@JsonPropertyOrder(
        SearchCriteria.JSON_PROPERTY_TEXT
)
@Generated("io.micronaut.openapi.generator.KotlinMicronautServerCodegen")
data class SearchCriteria(
    @Nullable
    @Schema(name = "text", requiredMode = Schema.RequiredMode.NOT_REQUIRED)
    @JsonProperty(JSON_PROPERTY_TEXT)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    var text: String? = null,
) {

    companion object {

        const val JSON_PROPERTY_TEXT = "text"
    }
}
```

### Environment Information

io.micronaut.openapi plugin version "4.4.0"

### Version

4.5.0
