### ISSUE TITLE
Default Values not working unless type is a String with enum values

### ISSUE THREAD

**Issue by scprek** [micronaut-projects/micronaut-openapi#1686]
### Expected Behavior

> [!NOTE]
> OpenApi's Kotlin generator just has default values in the comments, so micronaut's tool is already doing more
> `* @param contentType  (optional, default to "application/json")`

Have both the annotation mention a `defaultValue` correctly AND the paramater set to it. The `defaultValue` only being in the Annotation still requires you to define it when using the client and that is tedious for my use case. 

In general, I'd probably be better off generating some lower-level client than micronaut's Declarative client for 1 complex API we have and if that's the recommendation that's fine too. I need to modify the headers, path params, etc dynamically but most of the time the default is fine.

Given this spec

```yaml
paths:
  '/{apiVersion}/orders':
    get:
      summary: 'Browser/search multiple order'
      operationId: browseSearchOrders
      parameters:
        - $ref: '#/components/parameters/XFavorToken'
        - $ref: '#/components/parameters/XToken'
        - $ref: '#/components/parameters/ApiVersion'
components:
  parameters:
    ApiVersion:
      name: apiVersion
      in: path
      description: 'Api Version as a path parameter'
      required: true
      schema:
        type: string
        default: v5
    ContentType:
      name: Content-Type
      in: header
      required: false
      schema:
        type: string
        default: application/json
        nullable: true
    XFavorToken:
      name: X-Favor-Token
      in: header
      description: 'Legacy token header for v5 and older APIs'
      required: false
      schema:
        type: string
        default: null
        nullable: true
```

```kotlin
@Header(name = "X-Favor-User-Agent") @Nullable xFavorUserAgent: String? = null,
@PathVariable(name = "apiVersion", defaultValue = "v5") @Nullable apiVersion: ApiVersionParam? = "v5",
@Header(name = "Content-Type", defaultValue = "application/json") @Nullable contentType: String? = "application/json"
```

### Actual Behaviour

1. Defaults of null are ignored
2. Defaults that do not contain enum have double set of quotes around defaultValue
3. params are never set to default value, just the annotation.

```kotlin
@Header(name = "X-Favor-User-Agent") @Nullable xFavorUserAgent: String?,
@PathVariable(name = "apiVersion", defaultValue = ""v5"") @Nullable apiVersion: String?,
@Header(name = "Content-Type", defaultValue = ""application/json"") @Nullable contentType: String? 
```

Oddly if I make the apiVersion one a enum list of value and default to v5 it works

```yaml
components:
  parameters:
    ApiVersion:
      name: apiVersion
      in: path
      description: 'Api Version as a path parameter'
      required: false
      schema:
        type: string
        default: v5
        enum:
          - v1
          - v2
          - v3
          - v4
          - v5
          - v6
          - v7
```

```kotlin
@Header(name = "X-Favor-User-Agent") @Nullable xFavorUserAgent: String?,
@PathVariable(name = "apiVersion", defaultValue = "v5") @Nullable apiVersion: ApiVersionParam?,
@Header(name = "Content-Type", defaultValue = ""application/json"") @Nullable contentType: String? 
```

### Steps To Reproduce

```yaml
components:
  parameters:
    ApiVersion:
      name: apiVersion
      in: path
      description: 'Api Version as a path parameter'
      required: true
      schema:
        type: string
        default: v5
    ContentType:
      name: Content-Type
      in: header
      required: false
      schema:
        type: string
        default: application/json
        nullable: true
    XFavorToken:
      name: X-Favor-Token
      in: header
      description: 'Legacy token header for v5 and older APIs'
      required: false
      schema:
        type: string
        default: null
        nullable: true
```

### Version

4.5.1
