### ISSUE TITLE
There is no way to receive a file with Streaming using the OpenAPI generator

### ISSUE THREAD

**Issue by giovanabartholomeu** [micronaut-projects/micronaut-openapi#1721]
### Issue description

Swagger-codegen version
3.0.1

Description
When I generate a yaml to receive a file from the controller, by default it generates the CompletedFileUpload parameter:
  
```
requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
```

Generated interface:

```
@Post("/products")
    @Consumes("multipart/form-data")
    @Secured(SecurityRule.IS_ANONYMOUS)
    HttpResponse<@Valid Product> productsPost(
        @Nullable(inherited = true) CompletedFileUpload file
    );
```

Controller implements:

```
@io.micronaut.http.annotation.Controller
public class Controller implements DefaultApi {
    
    @Override
    public HttpResponse<@Valid Product> productsPost(CompletedFileUpload file) {
        return HttpResponse.ok(null);
    }
```

**But, I would like to upload files using StreamingFileUpload. How should I reference it in my yaml so that the generated parameter is a StreamingFileUpload and not a CompletedFileUpload?**

**Comment by altro3** [comment]
you are wrong, there is a way to do it. Just add type mapping via gradle plugin like this:
```groovy
    openapi {
        server(file("swagger.yml")) {
            useReactive = false
            typeMapping = [
                    file : "StreamingFileUpload"
            ]
        }
    }
```

**Comment by giovanabartholomeu** [comment]
Well, I use Maven instead of Gradle, so it only worked for me when I did it this way:
    
 ```
multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: StreamingFileUpload
                  format: binary
```

I didn’t need to import anything :) thanks
