### ISSUE TITLE
Kotlin Server Generator doesn't add default value to optional query params

### ISSUE THREAD

**Issue by KDanisme** [micronaut-projects/micronaut-openapi#1903]
### Expected Behavior

When generating a server with the koglin generator, parameters defined like this:
```
      parameters:
        - in: query
          name: brand
          schema:
            type: string
```
The generated interface should set the default value of the param to null:
```
        @QueryValue("brand") @Nullable brand: String? = null,
```

### Actual Behaviour

 The actual interface doesn't set that and generates this:
```
        @QueryValue("brand") @Nullable brand: String?,
```

### Steps To Reproduce

Gradle openapi config: 
```
micronaut {
    openapi {
        server(file("<whatever>")) {
            lang = "kotlin"
        }
    }
}

```

### Environment Information

`micronaut-openapi` version `6.13.2` 

### Version

4.7.6
