### ISSUE TITLE
Generated swagger file does not include provided examples

### ISSUE THREAD

**Issue by jwilson303** [micronaut-projects/micronaut-openapi#1970]
### Expected Behavior

I follow the [Micronaut guide for generating servers from OpenAPI definition](https://guides.micronaut.io/latest/micronaut-openapi-generator-server-gradle-java.html). I generate server code from the OpenAPI file and the micronaut-openapi plugin. I then add some examples under `components/examples` in the OpenAPI file. I expect that these examples get carried into the generated swagger file, under `build/classes/java/main/META_INF/swagger/api-spec.yml`.

### Actual Behaviour

The examples are not being carried into the generated swagger file. Therefore, when exposing the swagger docs via swagger UI, those examples are not present for the user to see.

### Steps To Reproduce

1. Follow the Micronaut Guide https://guides.micronaut.io/latest/micronaut-openapi-generator-server-gradle-java.html
2. In step 3.3, add the following code as an example:

```
components:  
    examples:
      BookInfoExample:
        value:
          name: "The Catcher in the Rye"
          availability: "available"
```

3. Run `./gradlew compileJava --console=verbose`
4. Observe the generated file in `build/classes/java/main/META_INF/swagger/micronautguide-1.0.0.yml` - the BookInfoExample is not there.

### Environment Information

MacOs (Sequoia 15.2)
Java 21

### Version

4.4.5

**Comment by altro3** [comment]
Could you add your final sample application-reproducer?

**Comment by jwilson303** [comment]
[micronautguide.zip](https://github.com/user-attachments/files/18704307/micronautguide.zip)

Here is the sample application.

**Comment by altro3** [comment]
The problem is that you are not using ready-made code, but code generated by openapi-generator . Openapi generator cannot add swagger annotations with examples to the generated code.

Look at the code that you generated and according to which the annotation processor then works:

<img width="1106" alt="Image" src="https://github.com/user-attachments/assets/9f9fce48-98b3-46e9-8a2d-e657e64771a8" />

micronaut-openapi should correctly add these examples. To do this, you need to put swagger annotations with the necessary values

**Comment by altro3** [comment]
It is not clear why you, given the existing openapi specification, would try to generate code, and then generate a specification again based on the generated code.

**Comment by jwilson303** [comment]
Many thanks for your help.

Essentially I wanted to serve my existing openapi specification on the `**/api-docs/` path, but I was not able to find micronaut examples on how to expose an existing openapi spec placed in the `src/main/resources` folder (and avoid generating one using the micronaut openapi plugin).

I was trying to follow micronaut examples, which led me down the path of using the open-api plugin which generated and exposed the file for me. I understand from you now that this was not the correct way.

I believe I have found a resolution, where I amended the static-resources path in my app.yml to the following:

```
  router:
    static-resources:
      swagger:
        paths: file:build/resources/main/api-spec
        mapping: /api-docs/**
```

Previously, it was looking in the META-INF location, which is used by the open-api plugin, I believe.
```
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /api-docs/**
```
