### ISSUE TITLE
ArraySchema item schema override broken

### ISSUE THREAD

**Issue by ideadapt** [micronaut-projects/micronaut-openapi#2082]
### Expected Behavior

```
@ArraySchema(schema = @Schema(implementation = String.class))
    public List<Pet> array = new ArrayList<>();
```

should result in 

```
        array:
          type: array
          items:
            type: string # <-- the overriden type
```

### Actual Behaviour

result is

```
        array:
          type: array
          items:
            allOf:
            - $ref: "#/components/schemas/Pet"
```

I discovered this bug when upgrading from micronaut-platform 4.7 to 4.8.0.

### Steps To Reproduce

1. Checkout branch of my fork. Diff at https://github.com/micronaut-projects/micronaut-openapi/compare/6.16.x...ideadapt:micronaut-openapi:array-schema-implementation-override?expand=1
2. Run the new test. See it fail.

### Environment Information

- MacOS
- openjdk version "21.0.3" 2024-04-16 LTS

### Example Application

https://github.com/ideadapt/micronaut-openapi/tree/array-schema-implementation-override

### Version

4.8.9
