### ISSUE TITLE
Flaky generation when extending non-empty interface

### ISSUE THREAD

**Issue by bastian-schlueter** [micronaut-projects/micronaut-openapi#2160]
### Expected Behavior

Given the following controller:
```java
@Controller
public interface MyController extends MyInterface {

  @Get
  String get(
      @QueryValue(defaultValue = "a") List<String> a,
      @QueryValue(defaultValue = "b") List<String> b);
}

interface MyInterface {
  @Post
  String set();
}
```

I would expect the following relevant part of the API spec for the `get` endpoint:
```yaml
paths:
  /:
    get:
      operationId: get
      parameters:
      - name: a
        in: query
        required: true
        explode: false
        schema:
          type: array
          items:
            type: string
          default:
          - a
      - name: b
        in: query
        required: true
        explode: false
        schema:
          type: array
          items:
            type: string
          default:
          - b
```

### Actual Behaviour

Actual output varies and is inconsistent.

One possible outcome looks like this:
```yaml
paths:
  /:
    get:
      operationId: get
      parameters:
      - name: b
        in: query
        required: true
        explode: false
        schema:
          type: array
          items:
            type: string
          default:
          - b
      - name: a
        in: query
        required: true
        explode: false
        schema:
          oneOf:
          - allOf:
            - type: array
              items:
                type: string
              default:
              - a
          - allOf:
            - type: array
              items:
                type: string
              default:
              - a
```

Notice the following:
1. order of parameters is wrong - `b` coming before `a` (varies between invocations)
2. parameters described as a `oneOf` with two identical options 

Very rarely this can also affect non-container types, for example `int`.

Sometimes this will happen to both parameters (pictured above),  sometimes only `a`, sometimes only `b` and very rarely none of them.

### Steps To Reproduce

1. have an interface as your controller
2. have an operation with 2 query values
3. both of them need to be container types
4. both of them need to have default values defined
5. let your controller interface extend an interface containing at least one method

Skip any of those steps and the behavior vanishes or at least doesn't appear consistently.

https://github.com/micronaut-projects/micronaut-openapi/issues/2151 was fixed with yesterday's release of `6.16.0`.
But with a non-empty interface, the behavior is back.

### Environment Information

```kotlin
plugins {
    id("io.micronaut.application") version "4.5.3"
    id("io.micronaut.aot") version "4.5.3"
    // ...
}

dependencies {
    annotationProcessor("io.micronaut.openapi:micronaut-openapi:6.16.0")
    compileOnly("io.micronaut.openapi:micronaut-openapi-annotations:6.16.0")
    // ...
}
```

### Version

4.8.2
