### ISSUE TITLE
@Parameter annotation ignores default value of "required" member

### ISSUE THREAD

**Issue by bastian-schlueter** [micronaut-projects/micronaut-openapi#2161]
### Expected Behavior

Given the following controller:
```java
@Controller
public interface MyController {

  @Get
  String get(
      @QueryValue @Parameter(description = "a") int a,
      @QueryValue @Parameter(description = "b", required = false) int b);
}
```

Considering the `required` member of the `@Parameter` annotation defaulting to `false`:
https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-annotations/src/main/java/io/swagger/v3/oas/annotations/Parameter.java#L69

I would expect both parameters to show up as not required in the generated spec:
```yaml
paths:
  /:
    get:
      operationId: get
      parameters:
      - name: a
        in: query
        description: a
        required: false
        explode: false
        schema:
          type: integer
          format: int32
      - name: b
        in: query
        description: b
        required: false
        explode: false
        schema:
          type: integer
          format: int32
```

### Actual Behaviour

However, the default value of `required` is ignored and query parameter `a` is generated as required:
```yaml
paths:
  /:
    get:
      operationId: get
      parameters:
      - name: a
        in: query
        description: a
        required: true
        explode: false
        schema:
          type: integer
          format: int32
      - name: b
        in: query
        description: b
        required: false
        explode: false
        schema:
          type: integer
          format: int32
```

Only if `required` is explicitly set to `false`, it will actually have an effect.

### Steps To Reproduce

1. annotate a parameter with `@Parameter`
2. observe it still being generated as required

### Environment Information

```kotlin
plugins {
    id("io.micronaut.application") version "4.5.3"
    id("io.micronaut.aot") version "4.5.3"
    // ...
}

dependencies {
    annotationProcessor("io.micronaut.openapi:micronaut-openapi:6.16.0")
    compileOnly("io.micronaut.openapi:micronaut-openapi-annotations:6.16.0")
    // ...
}
```

### Version

4.8.2
