### ISSUE TITLE
SecurityRequirements get parsed wrongly into the yaml

### ISSUE THREAD

**Issue by Chase22** [micronaut-projects/micronaut-openapi#22]
**What is the Error**
If using @SecurityRequirement on a controller or a method in a controller the resulting yaml file is not correct and will not work when using swagger UI

```java
@Validated
@Controller("/api/availabilities")
@SecurityScheme(type = SecuritySchemeType.APIKEY, 
                               name = "someName", 
                               in = SecuritySchemeIn.HEADER)
@SecurityRequirement(name = "someName")
class AvailabilitiesController @Inject constructor(private val tscClient: TscClient) {

@Post
fun getSlotsById(@Body @Valid timeslotRequest: AvailabilitiesRequestRvo): Single<MutableHttpResponse<List<TscSlotRvo>>> {
        // content ommited
}
```

this causes the following entry in the swagger-yaml file
```yml
paths:
  /api/availabilities:
    post:
      operationId: getSlotsById
      //...
      security:
      - name:
        - someName
```

correctly the yaml should contain the following:
```yml
paths:
  /api/availabilities:
    post:
      operationId: getSlotsById
      //...
      security:
      - someName: []
```
