### ISSUE TITLE
Swagger file generation does not obey snake_case setting for jackson

### ISSUE THREAD

**Issue by lenalebt** [micronaut-projects/micronaut-openapi#24]
I have a project where I configured jackson to use `snake_case` in JSON:

From `application.yml`:
```
jackson:
  property-naming-strategy: SNAKE_CASE
```

Schemas generated for my Kotlin data classes are generated with `camelCase`:
```
data class Foo(val hasChildren: Boolean)
```
leads to
```
components:
  schemas:
    Foo:
      type: object
      properties:
        hasChildren:
          type: boolean
```

`hasChildren` should be named `has_children`.

Are there any known workarounds?
