### ISSUE TITLE
Required property names are not translated when naming strategy is changed

### ISSUE THREAD

**Issue by nfode** [micronaut-projects/micronaut-openapi#240]
I changed the property naming strategy to `SNAKE_CASE` with the following setting:
`micronaut.openapi.property.naming.strategy=SNAKE_CASE`

Property names are now correctly translated to `SNAKE_CASE`, but if they are required their corresponding entries in the required list are not (See the example below). 

Example:
```
UserDTO:
  required:
    - systemRole
    - userId
    - username
  type: object
  properties:
   user_id:
     type: string
   username:
     type: string
   system_role:
     type: string
   email:
    type: string
  	nullable: true
```

I checked the code and found no code for required entries naming translation. So I guess it is not implemented.

If someone can give me some help how to implement translation for required entries then I would implement it.
