### ISSUE TITLE
Example of ZonedDateTime property isn't generated as a string

### ISSUE THREAD

**Issue by alphawolf1988** [micronaut-projects/micronaut-openapi#348]
Currently, the example of ZonedDateTime property isn't rendered as a string:

```
createdAt:
          type: string
          description: "The datetime the action, that is tracked, was executed by\
            \ the user. The format is ISO-8601."
          format: date-time
          example: 2013-02-15T12:00:00+01:00    <<<-------------------- Quotation is missing
```
