### ISSUE TITLE
Swagger view are not generated in micronaut 2.1.0

### ISSUE THREAD

**Issue by anandjaisy** [micronaut-projects/micronaut-openapi#355]
```
dependencies {
    annotationProcessor("io.micronaut.openapi:micronaut-openapi")
    implementation("io.micronaut:micronaut-validation")
    implementation("io.micronaut:micronaut-runtime")
    implementation("javax.annotation:javax.annotation-api")
    implementation("io.micronaut:micronaut-http-client")
    implementation("io.micronaut:micronaut-discovery-client")
    implementation("io.micronaut.rxjava3:micronaut-rxjava3")
    implementation("io.micronaut.kafka:micronaut-kafka")
    implementation("io.swagger.core.v3:swagger-annotations")
    runtimeOnly("ch.qos.logback:logback-classic")
}

tasks.withType(JavaCompile) {
    options.fork = true
    options.forkOptions.jvmArgs << '-Dmicronaut.openapi.views.spec=rapidoc.enabled=true,swagger-ui.enabled=true,swagger-ui.theme=flattop'
}
```

**openapi.properties**
`micronaut.openapi.views.spec=redoc.enabled=true,rapidoc.enabled=true,swagger-ui.enabled=true,swagger-ui.theme=flattop`

**Application.yml**

```
micronaut:
  application:
    name: feteBirdProduct
  server:
    port: 8083
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
        redoc:
          paths: classpath:META-INF/swagger/views/redoc
          mapping: /redoc/**
        rapidoc:
          paths: classpath:META-INF/swagger/views/rapidoc
          mapping: /rapidoc/**
        swagger-ui:
          paths: classpath:META-INF/swagger/views/swagger-ui
          mapping: /swagger-ui/**
```

![image](https://user-images.githubusercontent.com/1625641/94932123-f8b01300-050b-11eb-9cbe-f16d27dd261a.png)

Also tried the solution 

`annotationProcessor "io.micronaut.configuration:micronaut-openapi:1.3.3"`

But didn't work

- **Operating System**: Mac os Catalina
- **Micronaut Version:** 2.1.0
- **JDK Version:** 14
