### ISSUE TITLE
Duplicate operationId values

### ISSUE THREAD

**Issue by davidhiendl** [micronaut-projects/micronaut-openapi#361]
Currently the operationId for the OpenAPI spec is generated only from the simple method name (if not explicitly set).
This basically forces the use of `@Operation(operationId = "....")` for every non-unique endpoint method name to avoid conflicts in the generated spec.
This results in the need to add many additional annotations to resolve conflicts.

### Steps to Reproduce
Create 2 classes containing a identically named method without a `@Operation(operationId = "....")` annotation

```kotlin
@Controller("/test1")
class TestController {
    @Get("/")
    fun index(): String {
        return "Hello World"
    }
}

@Controller("/test2")
class TestController {
    @Get("/")
    fun index(): String {
        return "Hello World"
    }
}
```

After building the project both operations have the same operationId in the resulting OpenAPI spec.

### Expected Behaviour
It would be preferable if a unique operationId is generated from the full method path and HTTP method.
```yml
paths:
  /test1:
    get:
      operationId: test1Get
      ....
  /test2:
    get:
      operationId: test2Get
      ....
```

### Actual Behaviour
operationId is duplicate because only the method name is used when generating the operationId:

```yml
paths:
  /test1:
    get:
      operationId: index
      ....
  /test2:
    get:
      operationId: index
      ....
```

The relevant code is located here:
https://github.com/micronaut-projects/micronaut-openapi/blob/1f6c6e8560a6976e21a2c7a569885db7090408f1/openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiEndpointVisitor.java#L728

### Environment Information
- **Micronaut Version:** 2.1
