### ISSUE TITLE
Incorrect OpenAPI is generated for multi-dimensional arrays

### ISSUE THREAD

**Issue by rdesgroppes** [micronaut-projects/micronaut-openapi#367]
According to https://swagger.io/docs/specification/data-models/data-types/#array:

> [...] Arrays can be nested:
> ```yaml
>    # [ [1, 2], [3, 4] ]
>    type: array
>    items:
>      type: array
>      items:
>        type: integer
> ```
... but `micronaut-openapi` doesn't seem to support that feature yet.

### Steps to Reproduce

1. Declare a @Schema on a nested array type, for instance:
```java
@Schema
class MyClass
{
  @ArraySchema(arraySchema = @Schema(description = "int[][]"))
  public int[][] nestedInts;

  @ArraySchema(arraySchema = @Schema(description = "List<List<Integer>>"))
  public List<List<Integer>> nestedIntegers;
}
```

### Expected Behaviour

Nested arrays:
```yaml
components:
  schemas:
    MyClass:
      type: object
      properties:
        nestedInts:
          type: array
          description: "int[][]"
          items:
            type: array
            items:
              type: integer
              format: int32
        nestedIntegers:
          type: array
          description: List<List<Integer>>
          items:
            type: array
            items:
              type: integer
              format: int32
```

### Actual Behaviour

A "Flat" array for native integers (wrong depth), and an array of objects of type `List_Integer_` for the nested `List<Integer>`s:
```yaml
components:
  schemas:
    MyClass:
      type: object
      properties:
        nestedInts:
          type: array
          description: "int[][]"
          items:
            type: integer
            format: int32
        nestedIntegers:
          type: array
          description: List<List<Integer>>
          items:
            $ref: '#/components/schemas/List_Integer_'
    List_Integer_:
      type: object
      properties:
        empty:
          type: boolean
```

### Environment Information

(not relevant to the problem)
- **Operating System**: Ubuntu 20.04.1 LTS 
- **Micronaut Version:** 2.1.2
- **JDK Version:** openjdk version "1.8.0_272"

### Dependencies

- micronaut-projects/micronaut-core#2573 (Already an array exception in annotation processor)
- micronaut-projects/micronaut-core#3850 (Add support for multi dimensional arrays in introspections)
