### ISSUE TITLE
Improve support for @RequestBean, ignore static fields/constants. 

### ISSUE THREAD

**Issue by mikaelvik** [micronaut-projects/micronaut-openapi#392]
### Fix

This is (hopefully) an improvement to the solution from #369 . 

I've already found a simple solution and will submit a pull request. 

### Reproduce 

Create a @RequestBean class with a constant and a header field referencing the constant. 

```java
@Introspected
class MyRequestBean {

    public static final String HEADER_CONTENT_TYPE = "Content-type";

    @Header(HEADER_CONTENT_TYPE)
    private String contentType;

    // omitted
}
```

The generated openapi spec contains parameters for the constant and the field. 

```yml
# omitted ...
      parameters:
      - name: HEADER_CONTENT_TYPE
        in: query
        required: true
        schema:
          type: string
      - name: Content-type
        in: header
        required: true
        schema:
          type: string

```

### Expected Behaviour

The parameter `HEADER_CONTENT_TYPE` should not have been added.
