### ISSUE TITLE
Authorization code flow + PKCE setup with swagger UI 

### ISSUE THREAD

**Issue by anandjaisy** [micronaut-projects/micronaut-openapi#422]
Authentication with OKTA for the Micronaut swagger definition with Authorization flow + PKCE  cliendId and usePkceWithAuthorizationCodeGrant not added in the swagger final .yml file.

**Using security schema from the code** there is no option for **clientId** and **usePkceWithAuthorizationCodeGrant**

```
@SecurityScheme(name = "Open Id Connect",
        type = SecuritySchemeType.OAUTH2,
        scheme = "bearer",
        bearerFormat = "jwt",
        flows = @OAuthFlows(
                authorizationCode = @OAuthFlow(
                        authorizationUrl = "https://dev-6271510.okta.com/oauth2/default",
                        tokenUrl = "https://dev-6271510.okta.com/oauth2/default/v1/token",
                        refreshUrl = "",
                        scopes = {@OAuthScope(name = "openid"),
                                @OAuthScope(name = "profile"),
                                @OAuthScope(name = "email"),
                                @OAuthScope(name = "address"),
                                @OAuthScope(name = "phone"),
                                @OAuthScope(name = "offline_access")
                        }))
)
public class Application {}
```
**With Schema merging technique**

**security.yml**
```
components:
  securitySchemes:
    Open Id Connect:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://dev-6271510.okta.com/oauth2/default/v1/authorize
          tokenUrl: https://dev-6271510.okta.com/oauth2/default/v1/token
          refreshUrl: ""
          clientId: xxxxxxxxx
          usePkceWithAuthorizationCodeGrant: true
          scopes:
            openid: Open Id scope
            profile: Name scope
            email: Email scope

```
On the final .yml file the **clientId** and **usePkceWithAuthorizationCodeGrant** are not added using schema merging as well

![image](https://user-images.githubusercontent.com/1625641/102333861-fc542180-3fb3-11eb-94c5-cd4df576a6bb.png)
