### ISSUE TITLE
Merging the additional files content is not working

### ISSUE THREAD

**Issue by anandjaisy** [micronaut-projects/micronaut-openapi#438]
In the additional files, I have the below security schemes

```
securitySchemes:
  Open Id Connect:
    type: oauth2
    flows:
      authorizationCode:
        authorizationUrl: https://falconidentityserver.azurewebsites.net/connect/authorize
        tokenUrl: https://falconidentityserver.azurewebsites.net/connect/token
        refreshUrl: ""
        scopes:
          openid: Open Id scope
          profile: Name scope
          email: Email scope
        usePkceWithAuthorizationCodeGrant: true
```

**build.gradle**

```
tasks.withType(JavaCompile).all {
    options.fork = true
    options.forkOptions.jvmArgs << '-Dmicronaut.openapi.views.spec=swagger-ui.enabled=true,swagger-ui.theme=MATERIAL'
    options.forkOptions.jvmArgs << '-Dmicronaut.openapi.additional.files=src/main/resources/swagger'
    options.compilerArgs += ['--enable-preview']
}
```
the original file has no content of the security schema, here is the repo https://github.com/anandjaisy/micronuatswaggermerging

**Comment by asodja** [comment]
@anandjaisy your example will work if change it to (note `components`):
```
components:
  securitySchemes:
    Open Id Connect:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://falconidentityserver.azurewebsites.net/connect/authorize
          tokenUrl: https://falconidentityserver.azurewebsites.net/connect/token
          refreshUrl: ""
          scopes:
            openid: Open Id scope
            profile: Name scope
            email: Email scope
          usePkceWithAuthorizationCodeGrant: true
```

Reason for that is: micronaut.openapi annotation processor deserializes yaml to OpenAPI object. So if your yaml does not start at the root of OpenAPI, it won't be merged correctly.
