### ISSUE TITLE
Schemas are not generated for RxJava 3 response types

### ISSUE THREAD

**Issue by JamieCressey** [micronaut-projects/micronaut-openapi#440]
When returning RxJava 3 types from a controller, OpenApi schemas are not being generated correctly.

Example:

The following example controller, using RxJava 3;

```
import io.micronaut.http.annotation.Controller;
import io.micronaut.http.annotation.Get;
import io.reactivex.rxjava3.core.Single;
import lombok.AllArgsConstructor;
import lombok.Data;

@Controller("/testing")
public class TestController {
    @Get
    public Single<TestPOJO> get() {
        return Single.just(new TestPOJO("testing123"));
    }

    @Data
    @AllArgsConstructor
    public static class TestPOJO {
        private String testString;
    }
}
```

Generates the following spec snippet;

```
components:
  schemas:
    Single_TestController.TestPOJO_:
      type: object
```

Whereas following example controller, using RxJava 2;

```
import io.micronaut.http.annotation.Controller;
import io.micronaut.http.annotation.Get;
import io.reactivex.Single;
import lombok.AllArgsConstructor;
import lombok.Data;

@Controller("/testing")
public class TestController {
    @Get
    public Single<TestPOJO> get() {
        return Single.just(new TestPOJO("testing123"));
    }

    @Data
    @AllArgsConstructor
    public static class TestPOJO {
        private String testString;
    }
}
```

Generates the expected spec snippet;

```
components:
  schemas:
    TestController.TestPOJO:
      type: object
      properties:
        testString:
          type: string
```
