### ISSUE TITLE
Allowable values missing in generated OpenAPI (Swagger) YAML

### ISSUE THREAD

**Issue by VladimirKotl** [micronaut-projects/micronaut-openapi#522]
### Steps to Reproduce

1. Micronaut + Java project
2. build.gradle
```
dependencies {
    annotationProcessor("io.micronaut.openapi:micronaut-openapi")
    implementation("io.micronaut:micronaut-http-client")
    implementation("io.micronaut:micronaut-runtime")
    implementation("io.swagger.core.v3:swagger-annotations:2.1.9")
    runtimeOnly("ch.qos.logback:logback-classic")
    implementation("io.micronaut:micronaut-validation")
}
```
3. application.java
```
@OpenAPIDefinition(
    info = @Info(
            title = "My Project",
            version = "1.0.0",
            description = "Let's rock",
            contact = @Contact(name = "Me", email = "me@company.com")
    ) ,
    extensions = {
            @Extension(name="x-api-id",
                    properties = @ExtensionProperty(name = "x-api-id", value="xxxx-xxxx-xxxx-xxxx-xxxxx")
            ),
            @Extension(name="x-audience",
                    properties = @ExtensionProperty(name="x-audience", value="component-internal")
            )
    },
    servers = {
            @Server(
                url="http://localhost:8080",
                variables = {
                        @ServerVariable(
                                allowableValues = {"v1", "v2"},
                                name = "service-version",
                                defaultValue = "v1"
                        )
                })
    }
)
public class Application {
    public static void main(String[] args) {
        Micronaut.run(Application.class, args);
    }
}
```

### Expected Behaviour

I expected that "allowableValues" are generated in my swagger yml file 

```
...
servers:
- url: http://localhost:8080
  variables:
    service-version:
      enum:
      - v1
      - v2
      default: v1
...
```

### Actual Behaviour
Generated swagger file is 

```
...
servers:
- url: http://localhost:8080
  variables:
    service-version:
      default: v1
...
```

The missing part is
      enum:
      - v1
      - v2

### Environment Information

- **Operating System**: Windows 10
- **Micronaut Version:** 2.5.3
- **JDK Version:** 16.0.1.9
