### ISSUE TITLE
UUID schema parameter  is not detected as OpenAPI inbuilt type but as custom schema

### ISSUE THREAD

**Issue by swaechter** [micronaut-projects/micronaut-openapi#548]
### Expected Behavior

Let's say we have a `Greeting` class with a `message` that will be sent from `senderId` to `receiverId`. A schema would look like this:

```java
@Schema(description = "Represent a greeting between a sender and a reciever")
public class Greeting {

    @Schema(description = "Greeting message the receiver will get")
    private String message;

    @Schema(description = "ID of the sender")
    private UUID senderId;

    // Schema is annotated on the getter method bellow
    private UUID receiverId;

    public Greeting() {
    }

    public Greeting(String message, UUID senderId, UUID receiverId) {
        this.message = message;
        this.senderId = senderId;
        this.receiverId = receiverId;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public UUID getSenderId() {
        return senderId;
    }

    public void setSenderId(UUID senderId) {
        this.senderId = senderId;
    }

    @Schema(description = "ID of the receiver")
    public UUID getReceiverId() {
        return receiverId;
    }

    public void setReceiverId(UUID receiverId) {
        this.receiverId = receiverId;
    }
}
```

The OpenAPI schema should look like this:

```
    Greeting:
      type: object
      properties:
        message:
          type: string
          description: Greeting message the receiver will get
        senderId:
          type: string
          description: ID of the sender
          format: uuid
        receiverId:
          type: string
          description: ID of the receiver
          format: uuid
      description: Represent a greeting between a sender and a reciever
```

### Actual Behaviour

Instead we have two problem:

1.) I have to annotate `@Schema` on the class-attribute and not on the getter-method. Annotating `@Schema` for `receiverId` on the getter-method will generate this broken schema:

```
    Greeting:
      type: object
      properties:
        message:
          type: string
          description: Greeting message the receiver will get
        senderId:
          type: string
          description: ID of the sender
          format: uuid
        receiverId:
          $ref: '#/components/schemas/UUID'
      description: Represent a greeting between a sender and a reciever
```

So the workaround was to annotate all UUID `@Schema` on the class-attrbite and not the getter-method. But for other data types, I have to annotate on the getter-method. So it would be good to be exchangable wherever possible (I prefer class attribute annotations)

2.) Since Micronaut 3.0.0-RC1 this workaround doesn't work anymore. Switching from 3.0.0-M5 to 3.0.0-RC1 will generate the following broken schema for class-attribute **and** getter-method annotations together:

```
    Greeting:
      type: object
      properties:
        message:
          type: string
          description: Greeting message the receiver will get
        senderId:
          $ref: '#/components/schemas/UUID'
        receiverId:
          $ref: '#/components/schemas/UUID'
```

And in the Swagger UI:

![Bug8_1](https://user-images.githubusercontent.com/5626755/129355005-5651f3bc-026e-43af-b6d9-c839e5ce1ca1.png)

### Steps To Reproduce

1. git clone https://github.com/swaechter/openapiproblems
2. Build and start the project
3. Open the Swagger UI http://localhost:8080/swagger-ui/index.html#/Bug8/sendGreeting

### Environment Information

- Windows 10 x64
-  AdoptOpenJDK-16.0.1+9 (build 16.0.1+9)

### Example Application

https://github.com/swaechter/openapiproblems

### Version

3.0.0-M5/RC1
