### ISSUE TITLE
Non required fields are incorrectly marked as required in the swagger ui

### ISSUE THREAD

**Issue by sujeet100** [micronaut-projects/micronaut-openapi#587]
### Expected Behavior

the default value for required is false in the @Schema annotation, hence the generated swagger ui documentation should show respective fields as not required (without red asterisk) 
@Schema(description = "some description", implementation = Foo.class)

When the required value is explicitly set to false then the generated swagger ui documentation should show respective fields as not required (without red asterisk) 
@Schema(description = "some description", implementation = Foo.class, required = false)

### Actual Behaviour

The fields with default value for required in @Schema annotation are shown as required (with red asterisk) in the swagger UI

The fields with explicit false value for required in @Schema annotation are shown as not required (without red asterisk) in the swagger UI, which is expected.

### Steps To Reproduce

Add an annotation on a field
@Schema(description = "some description", implementation = Foo.class, required = false)
and run the application.
Access the swagger ui documentation.

### Environment Information

MAC
JDK16

### Version

3.0.1

**Comment by ilopmar** [comment]
This has probably to do with the constructor of the class. If a parameter is mandatory in the constructor, then it's required. To make sure, please share a small app that reproduces the problem and I'll take a look

**Comment by sujeet100** [comment]
Example application: https://github.com/sujeet100/micronaut-swagger-example
Check Person and Address classes. I have added comments on the fields about the expected and actual behavior.

**Comment by sujeet100** [comment]
The issue is because of the use of the `booleanValue` API from AnnotationValue
https://github.com/micronaut-projects/micronaut-core/issues/2387
The API does not consider the default value from the annotation.

I would like to contribute a PR to fix this issue.
Also the generated openapi documentation contains string array for required field with boolean value as strings
```
components:
  schemas:
    Address:
      required:
      - city
      type: object
      properties:
        city:
          required:
          - "true"
          type: string
          description: city
        country:
          required:
          - "false"
          type: string
          description: country
      description: address of the person
```
In the above example 
```
required:
      - city
```
is expected as per openapi specification
```
country:
          required:
          - "false"
```
is not needed and results in appearing in the swagger UI documentation too.
