### ISSUE TITLE
@SecurityScheme `paramName` not accounted for the `name`.

### ISSUE THREAD

**Issue by puneetbehl** [micronaut-projects/micronaut-openapi#59]
The following: 
```
@SecurityScheme(name = "BearerAuthCookie",
        type = SecuritySchemeType.APIKEY,
        in = SecuritySchemeIn.COOKIE,
        paramName = "JWT")
```
does not result into: 

```
  securitySchemes:
    BearerAuthCookie:
      type: apiKey
      name: JWT
      in: cookie
```
and instead the `name` is set to `BearerAuthCookie`. 
See [swagger-core/blob/v2.0.4/modules/swagger-annotations/src/main/java/io/swagger/v3/oas/annotations/security/SecurityScheme](https://github.com/swagger-api/swagger-core/blob/v2.0.4/modules/swagger-annotations/src/main/java/io/swagger/v3/oas/annotations/security/SecurityScheme.java#L71)
