### ISSUE TITLE
Kotlin data classes can have @NotNull fields marked as nullable in swagger output

### ISSUE THREAD

**Issue by davidjessop** [micronaut-projects/micronaut-openapi#611]
### Expected Behavior

For a request DTO;

```
data class SomeRequestDto(
    @field:NotNull val a: String?,
    @field:NotNull val b: String?,
    @field:NotNull val c: String?,
)
```

The fields are required but declared as nullable strings to allow the application to deserialise the request and validate it, even in the event that the client has omitted a field.

Since the fields are annotated as `@NotNull` I would expect them not to be marked as nullable in the swagger output

### Actual Behaviour

The `@NotNull` annotations cause the fields to be marked as _required_ but a `@javax.annotation.Nullable` annotation has been added which [causes them to the marked as nullable](https://github.com/micronaut-projects/micronaut-openapi/blob/299f1089e69ec05c77288078f796311c306618ef/openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java#L960)  in the output;

```
    SomeRequestDto:
      required:
      - a
      - b
      - c
      type: object
      properties:
        a:
          type: string
          nullable: true
        b:
          type: string
          nullable: true
        c:
          type: string
          nullable: true
```

### Version

3.1.0

**Comment by ilopmar** [comment]
This doesn't make sense to me. A field is either optional or not, but it can't be both things at the same time. What is happening is that kapt generates the following stub:

```java
@org.jetbrains.annotations.Nullable()
@javax.validation.constraints.NotNull()
private final java.lang.String a = null;
```

Which again doesn't make sense and that's why the output of the generated OpenApi is not what you expect.

If you want to make the fields optional, as it seems you want because you want _allow the application to deserialise the request and validate it, even in the event that the client has omitted a field._, then you need to remove the `@NotNull` annotation.

With a fields like `val d: String?,`, the generated OpenAPI is:

```yaml
...
components:
  schemas:
    SomeRequestDto:
      required:
        # "d" is not here
      type: object
      properties:
        ...
        d:
          type: string
          nullable: true

```

Which is what you want.

**Comment by jonnii** [comment]
@ilopmar this is also a problem for us too, the issue is if you make a arg to a type non-nullable then you get a bad request because the type cannot be deserialized so if we want to have the validation work we need to make the type non-nullable. This is an problem for all the validation annotations whether or not the type is null or not.

**Comment by ilopmar** [comment]
@jonnii can you please share a class and controller with your specific example? (I don't need a full application, just those two classes).

**Comment by jonnii** [comment]
@ilopmar redacted but should give you an idea:

```
@Validated
@Controller("/v1/customers")
class CustomersController{
    @Post
    @Status(HttpStatus.CREATED)
    @Secured("createCustomer")
    @ExecuteOn(TaskExecutors.IO)
    suspend fun createCustomer(
        @Valid @Body request: CreateCustomerRequest
    ): CustomerResponse {
        val customerName = request.customerName!!
    }

    @Introspected
    data class CreateCustomerRequest(
        @field:NotNull
        val customerName: String?,
    )
}
```

If we make the `customerName` a `String` then the validation never triggers because the entity cannot be created in order to validate it.

**Comment by djessop-nydig** [comment]
My situation is that I have request DTOs with a number of fields with a variety of validation annotations, e.g.

```
    @Introspected
    data class CreateCustomerRequest(
        @field:NotNull
        @field:Size(max=100)
        val customerName: String?,

        @field:NotNull
        @field:PastOrPresent
        val birthDate: LocalDate?,
    )
```

If a request violates the validation rules I want to return a response that reports all of the validation failures, e.g. if a client posts;
```
{
    "customerName" : null,
    "dateOfBirth" : "2043-01-01"
}
```

the response should report both that `customerName` must not be null and that `dateOfBirth` must not be in the future. The validation for the `@Size` and `@PastOrPresent` annotations is run after the `CreateCustomerRequest` is deserialised and (as @jonnii says), `CreateCustomerRequest` cannot be deserialised in this case if `customerName` is not a nullable field. So the fields are nullable from the JVM's perspective (it's possible to construct an instance of the class where the fields are null) but not nullable from the API perspective (the server will reject any request where either field is null).

**Comment by ilopmar** [comment]
Basically the problem here are Kotlin data classes. The following works as expected in Java:

```java
@Controller("/v1/customers")
public class CustomersController {

    @Post
    @Status(HttpStatus.CREATED)
    public void createCustomer(@Valid @Body CreateCustomerRequest request) {
    }
}

@Introspected
public class CreateCustomerRequest {

    @NotNull
    private String customerName;

    @NotNull
    @PastOrPresent
    private LocalDate birthDate;

    public CreateCustomerRequest() {
    }
    // getters and setters
}
```

It generates:

```yaml
...
components:
  schemas:
    CreateCustomerRequest:
      required:
      - birthDate
      - customerName
      type: object
      properties:
        customerName:
          type: string
        birthDate:
          type: string
          format: date
```

What happens, as mentioned before is that Kotlin generates the following stub:

```java
@io.micronaut.core.annotation.Introspected()
public final class CreateCustomerRequest {
    @org.jetbrains.annotations.Nullable()
    @javax.validation.constraints.NotNull()
    private final java.lang.String customerName = null;

    @org.jetbrains.annotations.Nullable()
    @javax.validation.constraints.PastOrPresent()
    @javax.validation.constraints.NotNull()
    private final java.time.LocalDate birthDate = null;
    
    public CreateCustomerRequest(@org.jetbrains.annotations.Nullable()
    java.lang.String customerName, @org.jetbrains.annotations.Nullable()
    java.time.LocalDate birthDate) {
        super();
    }

    @org.jetbrains.annotations.Nullable()
    public final java.lang.String getCustomerName() {
        return null;
    }
    
    @org.jetbrains.annotations.Nullable()
    public final java.time.LocalDate getBirthDate() {
        return null;
    }

   //...
}
```

Which again contains opposite annotations. Fields are annotated with both `@Nullable` and `@NotNull` but also the constructor uses `@Nullable`. 
What we do to decide if whether a property is requiered or not is checking it's nullability in the default constructor https://github.com/micronaut-projects/micronaut-openapi/blob/299f1089e69ec05c77288078f796311c306618ef/openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java#L825, and in this case it is nullable, so we set it to `nullable: true`

I not really sure how we can fix this properly. I only see hacks to do it...
