### ISSUE TITLE
Invalid stripping of `is` prefix from `Boolean` properties

### ISSUE THREAD

**Issue by morki** [micronaut-projects/micronaut-openapi#616]
### Expected Behavior

With following data class:
```kotlin
@Introspected
data class Account(
    val id: Int,
    val name: String,
    val isEnabled: Boolean,
)
```

This OpenAPI specification is generated:
```yaml
components:
  schemas:
    Account:
      required:
      - id
      - name
      - isEnabled
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        isEnabled:
          type: boolean
```

### Actual Behaviour

With the same code as above, the following OpenAPI specification is generated:
```yaml
components:
  schemas:
    Account:
      required:
      - id
      - name
      - enabled
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        enabled:
          type: boolean
```

### Steps To Reproduce

See above.

### Environment Information

Not applicable.

### Version

3.1.4
