### ISSUE TITLE
SecurityScheme annotation should populate the name property

### ISSUE THREAD

**Issue by mjohnston-il** [micronaut-projects/micronaut-openapi#633]
### Expected Behavior

When using a @SecurityScheme annotation like
```
@SecurityScheme(
	type = SecuritySchemeType.APIKEY,
	name = "MyScheme",
	`in` = SecuritySchemeIn.HEADER
)
```

The OpenApi schema file contains this definition:
```  
  securitySchemes:
    MyScheme:
      type: apiKey
      in: header
```

According to the `org.openapi.generator` openApiValidate task, this is invalid.  It complains that 
```
> There were issues with the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI).
   | Error count: 1, Warning count: 0
  Errors:
        -attribute components.securitySchemes.MyScheme.name is missing
```

I believe that if the `paramName` attribute is set, then we should use the name value.  Thus, the OpenApi schema should look like this:
```
  securitySchemes:
    MyScheme:
      name: MyScheme
      type: apiKey
      in: header
```

### Version

7.1.0
