### ISSUE TITLE
When a field has @field:Schema annotation, it is not listed as required

### ISSUE THREAD

**Issue by ruiminamywang** [micronaut-projects/micronaut-openapi#643]
### Expected Behavior

With micronaut 2.5.13, micronaut-openapi 2.6.2, language: Kotlin
```
@Introspected
data class SomeRequest(
    @field:Schema(description = "description ...")
    @field:NotBlank
    val name: String,
    @field:Schema(description = "description ...")
    val description: String? // Optional
)
```
The code above generates openAPI specs like
```
    SomeRequest:
      required:
      - name
      type: object
      properties:
        name:
          minLength: 1
          type: string
          description: description ...
        description:
          type: string
          description: description ...
          nullable: true
```

### Actual Behaviour

However, after upgrading to micronaut 3.1.4, and micronaut-openapi 3.2.0, `name` become optional after auto-generating the openAPI specs:
```
    SomeRequest:
      type: object
      properties:
        name:
          minLength: 1
          type: string
          description: description ...
        description:
          type: string
          description: description ...
          nullable: true
```

These lines are removed
```
      required:
      - name
```

### Steps To Reproduce

1. Use micronaut 3.1.4, and micronaut-openapi 3.2.0
2. Use the following data class
```
@Introspected
data class SomeRequest(
    @field:Schema(description = "description ...")
    @field:NotBlank
    val name: String,
    @field:Schema(description = "description ...")
    val description: String? // Optional
)
```
3. generate the openapi yaml file

### Version

micronaut 3.1.4, and micronaut-openapi 3.2.0
