### ISSUE TITLE
"There are duplicate parameter values" when validating yaml file generated by version 4.4+

### ISSUE THREAD

**Issue by meriouma** [micronaut-projects/micronaut-openapi#798]
### Expected Behavior

```
/resa/{uuid}/users/{userUuid}/services/{serviceCode}:
  get:
    summary: get user service
    operationId: getServiceForUser
    parameters:
    - name: uuid
      in: path
      description: The identifier
      required: true
      schema:
        type: string
    - name: userUuid
      in: path
      description: The user identifier
      required: true
      schema:
        type: string
    - name: serviceCode
      in: path
      description: The service code
      required: true
      schema:
        type: string
```

### Actual Behaviour

```
/resa/{uuid}/users/{userUuid}/services/{serviceCode}:
  get:
    summary: get user service
    operationId: getServiceForUser
    parameters:
    - $ref: '#/components/parameters/'
    - $ref: '#/components/parameters/'
    - $ref: '#/components/parameters/'
```

### Steps To Reproduce

YAML generated with this code and micronaut 3.5.4 and micronaut-openapi 4.3.0 yields the expected behaviour. Updating to 5.6.2 and micronaut-openapi yields the incorrect behaviour.
```
@Get("/{uuid}/users/{userUuid}/services/{serviceCode}")
@Operation(
    summary = "get user service",
    operationId = "getServiceForUser",
    parameters = [
        Parameter(
            name = "uuid",
            description = "The identifier",
            schema = Schema(implementation = String::class),
            `in` = PATH
        ),
        Parameter(
            name = "userUuid",
            description = "The user identifier",
            schema = Schema(implementation = String::class),
            `in` = PATH
        ),
        Parameter(
            name = "serviceCode",
            description = "The service code",
            schema = Schema(implementation = String::class),
            `in` = PATH
        )
    ],
)
fun getServiceForUser(
    @NotBlank uuid: String,
    @NotBlank userUuid: String,
    @NotBlank serviceCode: String,
): SomeSchema {
 ...
}
```

### Version

3.6.2
