### ISSUE TITLE
Annotating class property with default value also adds default value to the generated schema of the class

### ISSUE THREAD

**Issue by nfode** [micronaut-projects/micronaut-openapi#800]
### Expected Behavior

When having the following class:
```kotlin
data class TestDTO(
    @field:Schema(defaultValue = "false")
    val state: Boolean
)
```
The generated schema should look like the following:
```yml
TestDTO:
  type: object
  properties:
    state:
      type: boolean
      default: false
```

### Actual Behaviour

The generated schema looks like this:
```
TestDTO:
  type: object
  properties:
    state:
      type: boolean
      default: false
  default: "false"
```

The `default: "false"` should not be generated since it belongs to the state property and **not** the TestDTO. The current behavior results in problems with f.ex. openapi-generator because the validation fails.

### Steps To Reproduce

Also see example application.

Steps:
1. Annotate a property in a class that is generated to the schema
2. generate openapi-spec

### Environment Information

- Micronaut Openapi-Generator: 4.4.3

### Example Application

https://github.com/flip-corp/micronaut-bugreports-demo/tree/micronaut_openapi_generates_default_for_schema

### Version

3.6.2
