### ISSUE TITLE
redoc path requires trailing slash to properly resolve .js artifacts

### ISSUE THREAD

**Issue by dshick-nydig** [micronaut-projects/micronaut-openapi#829]
https://github.com/micronaut-projects/micronaut-openapi/blob/78ae9dd5b5fe928a0430efb9e5fafcf2e3e28eb5/openapi/src/main/java/io/micronaut/openapi/view/OpenApiViewConfig.java#L51

https://github.com/micronaut-projects/micronaut-openapi/blob/78ae9dd5b5fe928a0430efb9e5fafcf2e3e28eb5/openapi/src/main/java/io/micronaut/openapi/view/RedocConfig.java#L32

Due to this script tag's src being relative, a URL such as `https://service:port/redoc` will not load the `redoc.standalone.js` file correctly as it will look for it in `https://service:port/res/redoc.standalone.js` rather than `https://service:port/redoc/res/redoc.standalone.js`. In order to remain irreverent of the trailing slash, the route without the trailing slash should redirect to include it, or the script src should be expanded to be relative only to the TLD, e.g. ...

```java
private static final String DEFAULT_REDOC_JS_PATH = "/" + OpenApiViewConfig.REDOC + "/" + OpenApiViewConfig.RESOURCE_DIR + "/redoc.standalone.js";
```

**Comment by altro3** [comment]
@dshick-nydig Hi! Could you give me simple service example with your configuration? I already fixed something in PR #824 and I need to understand your case, maybe this is solved using the current properties.

**Comment by edeesis** [comment]
You can work around this by adding res to your mappings, but this should be either added to the documentation or fixed.
```
      res:
        paths:
          - classpath:META-INF/swagger/views/swagger-ui/res
          - classpath:META-INF/swagger/views/rapidoc/res
          - classpath:META-INF/swagger/views/redoc/res
        mapping: /res/**
```

(obviously you don't need all 3, just wanted to include all 3 as an example)
