### ISSUE TITLE
[Regression. Critical] JS, CSS resources are not loaded, returns 404

### ISSUE THREAD

**Issue by meiblorn** [micronaut-projects/micronaut-openapi#841]
### Expected Behaviour

Expected behaviour: **resources to be loaded.**

### Screenshot for Micronaut OpenAPI 4.5.2:

![image](https://user-images.githubusercontent.com/4069585/201751564-2f172a02-0c85-4f70-8642-27c54bce3ece.png)

### Actual Behaviour

Actual behaviour: **resources are not accessible and not loaded.**

### Screenshots for Micronaut OpenAPI 4.6.0:

![image](https://user-images.githubusercontent.com/4069585/201752246-0034fe86-841b-4593-81a3-6318ecb20521.png)

![image](https://user-images.githubusercontent.com/4069585/201750997-0c21825c-ce7d-40e7-ac8d-78edb7f52c56.png)

### Steps To Reproduce

First, I create `openapi.properties` in the project root:
```
redoc.enabled=true
rapidoc.enabled=true
swagger-ui.enabled=true
swagger-ui.theme=flattop
```

Then, I start an application with the following properties at `application.yml`:
```
micronaut:
  router:
    static-resources:
      static:
        enabled: true
        paths:
          - "classpath:/static"
        mapping: "/static/**"
      swagger:
        enabled: true
        paths:
          - "classpath:/META-INF/swagger"
        mapping: "/swagger/**"
      swagger-ui:
        enabled: true
        paths:
          - "classpath:/META-INF/swagger/views/swagger-ui"
        mapping: "/swagger-ui/**"
      redoc:
        enabled: true
        paths:
          - "classpath:/META-INF/swagger/views/redoc"
        mapping: "/redoc/**"
      rapidoc:
        enabled: true
        paths:
          - "classpath:/META-INF/swagger/views/rapidoc"
        mapping: "/rapidoc/**"
```

After, I try to access `http://localhost:8080/swagger-ui/index.html`
It successfully opens `index.html` file, but **resources (js, css) are not loaded** because
`openapi processor` generates the following html:
```
<!doctype html>
<html lang='en'>

<head>
    <meta charset='UTF-8' />
    <title>krugit-user-service-1.0.0</title>
    <link rel='icon' type='image/png' href='swagger-ui/res/favicon-32x32.png' sizes='32x32' />
    <link rel='icon' type='image/png' href='swagger-ui/res/favicon-16x16.png' sizes='16x16' />
    <script src='swagger-ui/res/swagger-ui-bundle.js'></script>
    <script src='swagger-ui/res/swagger-ui-standalone-preset.js'></script>
    <link rel='stylesheet' type='text/css' href='swagger-ui/res/swagger-ui.css' />
    <link rel='stylesheet' type='text/css' href='swagger-ui/res/flattop.css' />
    
</head>
```

Notice paths there: **they are relative** to `index.html`, **NOT ABSOLUTE**
it means, browser expects `swagger-ui-bundle.js` to be at `http://localhost:8080/swagger-ui/swagger-ui/res/swagger-ui-bundle.js`. And same applies to other css, js resources.

![image](https://user-images.githubusercontent.com/4069585/201750997-0c21825c-ce7d-40e7-ac8d-78edb7f52c56.png)

---

### I've made research and found where is an issue:

See PR: https://github.com/micronaut-projects/micronaut-openapi/commit/05ac9a70c34b2772035e13daa64a4f3643357123 

Here is a previous implementation (how it was):
```java
    protected String getFinalUrl(VisitorContext context) {
        if (isDefaultJsUrl) {
            String contextPath = OpenApiApplicationVisitor.getConfigurationProperty("micronaut.server.context-path", context);
            if (contextPath == null) {
                contextPath = StringUtils.EMPTY_STRING;
            }
            String finalUrl = contextPath + (contextPath.endsWith("/") ? resourcesContextPath.substring(1) : resourcesContextPath);
            if (!finalUrl.endsWith("/")) {
                finalUrl += "/";
            }

            return finalUrl;
        }

        return jsUrl;
    }
```

And a new one (how it is now):

```java
protected String getFinalUrlPrefix(OpenApiViewConfig.RendererType rendererType, VisitorContext context) {
        String contextPath = OpenApiApplicationVisitor.getConfigurationProperty("micronaut.server.context-path", context);
        if (contextPath == null) {
            contextPath = StringUtils.EMPTY_STRING;
        }
        String finalUrl = contextPath + (contextPath.endsWith("/") ? resourcesContextPath.substring(1) : resourcesContextPath);
        if (!finalUrl.endsWith("/")) {
            finalUrl += "/";
        }

        return rendererType.getTemplatePath() + finalUrl;
    }
```

Let's debug it side by side:

| Assumptions  | How it was |  How it is now |
|---|---|---|
| isDefaultJsUrl = true; contextPath = null  | returns "res/"   | returns "swagger-ui/res/"   |

### Environment Information

- Micronaut OpenAPI 4.6.0

### Version

3.7.3
