### ISSUE TITLE
When using a non-default path for swagger-ui the js and css resources cannot be loadad

### ISSUE THREAD

**Issue by gaetjen** [micronaut-projects/micronaut-openapi#910]
This was introduced when I upgraded Micronaut from 3.7.4 to 3.8.0.

### Expected Behavior

When setting the following properties in `application.yml` the swagger-ui should work at `baseurl/customPath`
```yaml
micronaut:
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /customPath/**
```

### Actual Behaviour

The `index.html`still uses the default paths to reference js and css resources.
Excerpt:
```html
<script src='/swagger-ui/res/swagger-ui-bundle.js'></script>
<script src='/swagger-ui/res/swagger-ui-standalone-preset.js'></script>
<link rel='stylesheet' type='text/css' href='/swagger-ui/res/swagger-ui.css' />
<link rel='stylesheet' type='text/css' href='/swagger-ui/res/flattop.css' />
```
As a result, the swagger-ui page is just blank.

### Steps To Reproduce

Build and run linked repo, open http://localhost:8080/customPath

### Environment Information

- Ubuntu version 22.04
- Jdk version: 17
- Language: Kotlin

### Example Application

https://github.com/gaetjen/openapi-bug

### Micronaut Version

3.8.0, 3.8.1

### Workaround

A possible, but not ideal workaround is to explicitly set the resources path back to the default in the application.yml:
```yaml
      swagger-ui-res:
        paths: classpath:META-INF/swagger/views/swagger-ui/res
        mapping: /swagger-ui/res/**
```
Or you can use the default location for the swagger-ui (i.e. http://baseUrl/swagger-ui)
