### ISSUE TITLE
Enum string with special character not quoted in yaml

### ISSUE THREAD

**Issue by StefanSrf** [micronaut-projects/micronaut-openapi#974]
### Expected Behavior

Enum-strings with special characters should be quoted in yaml.

Example:
```
enum class DemoEnum {
    @JsonProperty("escaping-dash")
    ESCAPING_DASH,
    @JsonProperty("noEscaping")
    NO_ESCAPING
}
```
should result in 
```
    DemoEnum:
      type: string
      enum:
      - 'escaping-dash'
      - noEscaping
```

### Actual Behaviour

Invalid string in yaml, e.g. escaping-dash instead of 'escaping-dash'
```
    DemoEnum:
      type: string
      enum:
      - escaping-dash
      - noEscaping
```

### Steps To Reproduce

see example in Expected Behavior

### Environment Information

- Ubuntu
- JDK 11

### Version

3.8.7
